baseURL: "https://wonderful-swanson-f65e38.netlify.com"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
outputs:
  home:
    - HTML
    - JSON
  page:
    - HTML
    - JSON
  section:
    - HTML
    - JSON

# disableKinds:
#   - "section"
#   - "taxonomy"
#   - "taxonomyTerm"
#   - "RSS"
#   - "sitemap"
footnoteReturnLinkContents: "â†©"
googleAnalytics: ""
languageCode: "pt-br"
menu:
  header:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "data"
    name: "Dados"
    url: "/dados/"
    weight: 2
  - identifier: "project"
    name: "Projeto"
    url: "/projeto/"
    weight: 3
  - identifier: "pesquisas"
    name: "Pesquisas"
    url: "/pesquisas/"
    weight: 4
  - identifier: "inspire"
    name: "Inspire-se"
    url: "/inspirese/"
    weight: 5
  - identifier: "news"
    name: "Novidades"
    url: "/novidades/"
    weight: 6
  - identifier: "contact"
    name: "Contato"
    url: "/#contato"
    weight: 7
metaDataFormat: "yaml"
title: "Eduquidade"
params:
  mailchimpNewsletterFormAction: ""
  siteDescription: ""
  tagline: ""
  twitterUsername: "appcivico"
  shareImages:
    default: "images/sharing/Compartilhamento_blockchain.jpg"
    twitter: "images/sharing/Compartilhamento_twitter.jpg"
    facebook: "images/sharing/Compartilhamento_blockchain.jpg"
  socialNetworksLinks:
    twitter: "https://twitter.com/appcivico"
    # medium: "https://medium.com/app-civico"
    facebook: "https://www.facebook.com/AppCivicoCSB"
    # github: "https://github.com/AppCivico"
    youtube: "https://www.youtube.com/channel/UCIuAzzWMogJV0r-mvFmjNNQ"
taxonomies:
  tag: tags
  pais: paises
  area: areas
